#!/usr/bin/env python3
from pymatgen.io.vasp import Vasprun as pymvasprun
import numpy as np 
import gnuplotlib as gp
import termplotlib as tp

force = pymvasprun('./vasprun.xml')
tot = []
for i in range(0,len(force.as_dict()['output']['ionic_steps'])):
    x = [x2[0] for x2 in force.as_dict()['output']['ionic_steps'][i]['forces']]
    y = [y2[1] for y2 in force.as_dict()['output']['ionic_steps'][i]['forces']]
    z = [z2[2] for z2 in force.as_dict()['output']['ionic_steps'][i]['forces']]
    total = np.amax([np.sqrt(x[i]**2 + y[i]**2 + z[i]**2) for i in range(0,len(x))])
    tot.append(total)
    
x = [x for x in range(1,len(tot)+1)]
tot = np.array(tot)
x = np.array(x)
gp.plot((x,tot),terminal='dumb 60,20',unset='grid')


fig = tp.figure()
fig.plot(x,tot,width=60,height=20,label='Fmax')

fig.show()
    
